### ISSUE TITLE
Plugin reports "Your emails have been scheduled for delivery!" regardless of success.

### ISSUE THREAD

**Issue by bartonski** [bywatersolutions/koha-plugin-patron-emailer#4]
I queued a file which contained bad csv; but the plugin reported ""Your emails have been scheduled for delivery!" none-the-less.

There is no check that `$csv->column_names(@$column_names);` is correct, nor do we check for errors after the rest of the lines are read from the file.

**Comment by WNickC** [comment]
This should be fixed now
